### ISSUE TITLE
can't render model (adblock did it)

### ISSUE THREAD

**Issue by robsgarcia** [FWeynschenk/ppBricks#1]
i was able to use your site on my iPad with no issue, but when i try on my macbook i get failed to render model. i used both chrome and safari.

**Comment by FWeynschenk** [comment]
I might have reset the backend right as you were using it, can you try again?

It might also happen when you pick a very large object like 50x50 that hasn't been rendered before. The connection can time out before it's done. In that case it will have rendered on the backend and trying it again with the same exact settings a few minutes later should work.

**Comment by robsgarcia** [comment]
still having the same thing. all i am trying to do is render the default that comes up.

**Comment by FWeynschenk** [comment]
Does it say anything in the console? Ctrl-shift-i 

I'll check the logs. 

What are the settings at? Including modifiers.

**Comment by robsgarcia** [comment]
![Screen Shot 2022-01-12 at 11 47 44 AM](https://user-images.githubusercontent.com/63883179/149184630-83600991-f833-4c02-b9ef-2475842b7c62.png)

**Comment by FWeynschenk** [comment]
Strange question but is you computers time/date accurate?

**Comment by robsgarcia** [comment]
yes

**Comment by robsgarcia** [comment]
got it!!! ad blocker. disabled and everything worked.
