### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by robsgarcia** [FWeynschenk/ppBricks#13]
Looks like your certs have expired. Thanks, Rob

**Comment by FWeynschenk** [comment]
Maybe you caught while it was renewing. Is it working now?

**Comment by robsgarcia** [comment]
Talk about bad timing. Working fine for me now. Thanks,RobSent from Rob Garcia's iPhoneOn Dec 10, 2022, at 6:13 PM, FWeynschenk ***@***.***> wrote:﻿
Maybe you caught while it was renewing. Is it working now?
