### ISSUE TITLE
No studs on bottom of plates

### ISSUE THREAD

**Issue by geriweg** [FWeynschenk/ppBricks#14]
Hello,

i tried some plates and do not get any studs on the bottom.

Settings:
Type: plate
Top Type: studs

Rendered image (and also downloaded stl file) does not contain any studs on the bottom.

Did i miss any setting for this?

Thanks,
geri

**Comment by FWeynschenk** [comment]
Hey,

To get a plate with bottom profile you need to use type regular and lower the height to 3.2.

I've had this question before, I think I'm going to make it clearer what each type is.

Thanks for the feedback!
