### ISSUE TITLE
Temporarily offline due to moving the backend server. Be back soon

### ISSUE THREAD

**Issue by FWeynschenk** [FWeynschenk/ppBricks#15]

**Comment by N-Mi** [comment]
Hi,

Is this maintenance completed ? I tried to create a custom brick and the "Loading" message seems to spin forever.

edit : it then displayed "Failed to render model"

Thanks for you work on this project !

**Comment by FWeynschenk** [comment]
Should be functional now, particularly large models can take a while to render and send. I've been a little naive and it can time out while waiting. It should have rendered on the backend tho. If you try the same model with the exact same settings again a couple minutes later it should be fast enough!

Let me know if it still doesnt work.

**Comment by N-Mi** [comment]
Hmm... Tried a few times to generate a 6x16 plate with default settings, failed each time.

**Comment by FWeynschenk** [comment]
Strange, seems to work for me. Does it say anything in the console? (Ctrl-shift-i).

**Comment by FWeynschenk** [comment]
For some reason I can't seem to get it working over 4g, while it used to work before.  A home connection(wifi/ethernet) seems to work fine. I'll make an issue for it, don't know when I can fix it unfortunately.

Do you happen to be on a mobile connection?

**Comment by N-Mi** [comment]
> Strange, seems to work for me. Does it say anything in the console? (Ctrl-shift-i).

Seems there is a CORS issue in the console : 
`Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://bp508.hopto.org:3847/. Raison : échec de la requête CORS. Code d’état : (null).`

(sorry, my Firefox is in french).

> For some reason I can't seem to get it working over 4g, while it used to work before. A home connection(wifi/ethernet) seems to work fine. I'll make an issue for it, don't know when I can fix it unfortunately.
> 
> Do you happen to be on a mobile connection?

I'm behind a fiber connection. From the error message and the fact that it works from your home connection but not from 4G, I would guess the backend server is allowing requests only from your home IP address, or maybe a wrong "Access-Control-Allow-Origin" (server side) or "Origin" (client side) header in the request.

**Comment by FWeynschenk** [comment]
Yep, my ISP seems to have double nat-ed me. 

Thx for helping me find the problem, hope I can fix it soon.

**Comment by FWeynschenk** [comment]
Should be working now! Tysm for letting me know!

**Comment by N-Mi** [comment]
I can confirm it works now. Thanks for fixing !
