### ISSUE TITLE
Stl tinkercad problem

### ISSUE THREAD

**Issue by csepiy** [FWeynschenk/ppBricks#16]
I have generated some beams on https://flwe.nl/ppBricks/ and imported the stl files in tinkercad.com to make some 3d objects beam compatible. However beams look good in prusaslicer, but quite terrible in tinkercad. I guess, something is wrong in the generated stl files.

**Comment by FWeynschenk** [comment]
That makes sense unfortunately. To get decent performance out of OpenScad I had to disable making the results fully correct/watertight. None of the slicers I tried have problems with the stls it spit out, but modelling software doesn't like it.

**Comment by csepiy** [comment]
I was looking for beams having correct size after printing, so your generator was really promising. Any chance to add such a result? Or any idea how to convert the stls to modelling sw friendly?

**Comment by FWeynschenk** [comment]
Something like [meshmixer](https://meshmixer.com/) can probably fix it, haven't tried it myself recently.
