### ISSUE TITLE
cant render (certificate out of date)

### ISSUE THREAD

**Issue by robsgarcia** [FWeynschenk/ppBricks#2]
here is the error in the inspector. looks like a cert issue.

Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
index.js:87 default
index.js:54          POST https://bp508.hopto.org:3847/ 
net::ERR_CERT_AUTHORITY_INVALID
renderStl @ index.js:54
mainBtnClick @ index.js:91
eval @ VM960:3
index.js:74 TypeError: Failed to fetch
    at Proxy.renderStl (index.js:54:9)
    at Proxy.mainBtnClick (index.js:91:22)
    at HTMLButtonElement.eval (eval at Re (petite-vue.es.js:1:7947), <anonymous>:3:26)

**Comment by FWeynschenk** [comment]
Thanks for the bug report! I did set up an automatic certificate renewal but forgot to restart the service so it continued using the old one. Should be fixed now!
