### ISSUE TITLE
not rendering

### ISSUE THREAD

**Issue by jprokopowich** [FWeynschenk/ppBricks#3]
not rendering bricks. tried with FF and Chrome. see attached.
![Screenshot 2022-10-26 at 13-57-17 Perfect Printable Bricks](https://user-images.githubusercontent.com/7526760/198112857-12b22336-1f16-4927-a4f6-700132df6e90.png)

**Comment by FWeynschenk** [comment]
Is it working now? I've had some problems with my server but it should be fine now.

**Comment by jprokopowich** [comment]
yes ... thanks. great service.
