### ISSUE TITLE
Technic plate holes missing, plates have no bottom geometry

### ISSUE THREAD

**Issue by VanessaE** [FWeynschenk/ppBricks#4]
2xN plates shipped as part of the Technic range of parts can have axle-sized round holes centered between the studs, but no option exists to generate them with this tool.

![2x4 technic plate](https://user-images.githubusercontent.com/1733537/198827962-827b7fc9-b2db-4a66-bd64-b8e993c863d4.jpg)

Also, plates are missing the bottom-side geometry that's needed to snap them on top of other bricks - they're just flat and solid.

**Comment by FWeynschenk** [comment]
My terminology is kinda off. For plates with bottom geometry select `type: regular` and height: `3.2`.

I like the feature suggestion! I'll put it on my todo list!
