### ISSUE TITLE
Tube offsets glitch

### ISSUE THREAD

**Issue by VanessaE** [FWeynschenk/ppBricks#6]
I'm trying to calibrate my offsets and such, making a normal full height 4x4 brick, and have run into an issue...

If I set the tube inner offset to -0.06 or lower, the site throws an error, "(!) failed to render model", but without telling me what actually went wrong.

It will also throw that error if I set the tube \*outer* offset to anything higher than +0.08.

Outer offset at 0.08 and inner at -0.04 works fine, but my printer and the filament I'm using for this calibration are themselves dialed-in very sharply, so even with those offsets, the resulting print is just a hair less snug compared to a "real" brick, when fitting another "real" brick into or between the printed brick's tubes (at least, when using PETG).

![image](https://user-images.githubusercontent.com/1733537/199993711-60326df2-4206-466d-9f4a-66303e3f9c30.png)

**Comment by VanessaE** [comment]
![image](https://user-images.githubusercontent.com/1733537/199993537-dcb2c53e-93ea-4a41-a147-5a1f7c834328.png)

**Comment by FWeynschenk** [comment]
It should be fixed now!

Update broke a dependency on my backend. It was only returning models that were already rendered in the past...

(note to self, reinstall openscad `snap remove openscad-nightly; snap install openscad-nightly` after OS update)

**Comment by VanessaE** [comment]
Yep, it works now.
