### ISSUE TITLE
[FR] stud base flare compensation

### ISSUE THREAD

**Issue by VanessaE** [FWeynschenk/ppBricks#8]
In a lot of 3d-printed projects, any kind of small vertical projection rising from a flat horizontal surface will have some minuscule amount of "flaring" at its base, especially if the projection is hollow.  I believe this is because the hollow parts are able to shrink a little as the part fan cools them, compared to the base where it's solid enough to mostly avoid this effect.

This happens on Technic-style hollow studs as well.  While the "flaring" effect is tiny here, it gives the studs a slight outward taper at the bottom, which tends to push the bricks apart a tiny bit, making the fit not quite, well... perfect. :wink: 

Since slicers can't compensate for this effect (as far as I know), I would suggest giving the user an option to shrink the outer diameter of the stud's base slightly.  Although solid studs don't seem to have this "flaring" issue, it would probably be a good idea to let this adjustment apply to them also, just in case.

Shown below is a mock-up wherein I've subdivided the stud at 0.4 mm above the brick's top surface, and then reduced the stud base's outer diameter by 0.2 mm:

![image](https://user-images.githubusercontent.com/1733537/200055942-0ba835e0-0537-46b1-8f51-2adbeb308c5c.png)

I don't think it's necessary to make the starting height of this taper configurable.  A fixed starting point of 0.4 mm will probably be fine for most users.  That is, unless you're bored enough to add it. :sweat_smile:

**Comment by FWeynschenk** [comment]
I had considered this but it was more complicated than I wanted (using openscad) and most slicers have at least something that tries to mitigate this issue. It's definitely still on the maybe-to-do-in-the-future list.

For prusaslicer there is [elephant foot compensation](https://help.prusa3d.com/article/elephant-foot-compensation_114487) and in Cura [Initial layer horizontal expansion](https://support.ultimaker.com/hc/en-us/articles/360012512340-Wall-settings#:~:text=Initial%20layer%20horizontal%20expansion)

**Comment by VanessaE** [comment]
Elephant's foot compensation only works on a part's first few layers, and besides, that's caused by a different mechanism than what causes this flaring.

**Comment by FWeynschenk** [comment]
Ah I glossed over the stud part. My parts don't seem to have this problem. I do usually tune my profiles to 95-97% flow-rate for top layers, that might have hidden this.

**Comment by VanessaE** [comment]
Right, this is for the studs, so you'll probably want to reopen this request.  :smile:
